### ISSUE TITLE
[Bug] Admin not able to see submitted video link

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#10]
**Describe the bug**
Admin not able to see submitted video link

**To Reproduce**
1. On the tournament management, after players have submitted a video link
2. Click view evidence 
3. When looking at the submitted evidence, you will see the screenshot that is uploaded, but for the video, it doesn't tell that this is a video link, and when you click on it it doesn't really take you to that video link seems like the URL need to be fixed (please see GIF below)

**Expected behavior**
The admin should see a submitted video link from here, and clicking on it should take the admin to that linked website

**Screenshots**
https://gyazo.com/94052a3a49888989dc800c7373432dbc

![Image](https://github.com/edosdigital/issues/assets/151843786/334819dc-01ec-4d39-a044-d2312195e6ff)

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/3dc30be96d8c4ad9e467ea47e032429b
