### ISSUE TITLE
[Bug] Matches with both participants auto forfeit fail to advance match bracket and next round matches

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#103]
**Describe the bug**
_If a match has both of its participants forfeited due to unable to ready up in time, the tournament will not advance any participants to the next round and the brackets that are connected to this match will remain TBD._

**Expected behavior**
_Should a match have both participants forfeited, one should be picked to advance the bracket and rounds. 

Alternatively, the next rounds could have BYE matches if the earlier match have both participants forfeited._  

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://prnt.sc/kJw9ZWP5K9qv
https://gyazo.com/6d6bb8ee5707f2e2dd00811f64c1a11d

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/446pwhmnyqnjdy6vcvgdd7d740
https://battle.staging.gosugamers.net/tournament/4f3zfx407eaz86s2n0e3bxgcn4#schedule

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**
_Before, the rule for both participants who auto forfeit was that the left side participant will always advance to the next round. Tournament admins can also manually advance who will go to the next round to able to fix this issue manually._

**Comment by JayWongjedjan** [comment]
Currently, there are no automatic bye, it left the next match with TBD opponent
https://gyazo.com/284b9473134bb7faaaa5465472960812

**Comment by EJNiones** [comment]
Auto Bye on forfeit verified:

https://gyazo.com/16826e2f91664785e9cda4f59fa64c4c

https://gyazo.com/c92e7dcb73f72b716c8c5530accc897b
