### ISSUE TITLE
[Bug] FFA -  Encountering error when submitting scores

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#105]
**Describe the bug**
_Participants will encounter an error when submitting their scores._ 

**To Reproduce**
_1. I am registered user
2. I have registered to a live FFA tournament
3. I have a match that already live
4. On my match page, I attempt to submit my scores
5. I encounter an error was I have inputted my scores and click on submit_

**Expected behavior**
_Participants should be able to submit scores without encountering errors._ 

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/7b737a8fdf7ae80b9f2010dddc891bad
https://gyazo.com/e9de9ef73805ed0b8cd6d401230062b2

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/4m9mvndj4pt805e2zft6yr13d2

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**
_Users also are only able to submit their own scores. Earlier versions, participants are able to give scores to their opponents along side theirs._

**Comment by EJNiones** [comment]
Maybe related to issue #93

**Comment by Yusuf-** [comment]
@EJNiones I created a new FFA tournament and enforced some scores. It all went fine.
Can you retest this one and #93?

**Comment by EJNiones** [comment]
Confirmed fixed.
