### ISSUE TITLE
[Bug] Score submission not working on manual mode

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#106]
**Describe the bug**
Submitting scores doesn't complete the match or advance to score review in manual mode. It does show on the admin side while enforcing the scores. Tested with auto tournament and score submission works just fine 

Added info 
After using admin to enforce a score on round 1 this is what I see when trying to submit a score on round 2
Tournament link: https://battle.staging.gosugamers.net/tournament/4hqx3a3s84k831rwsjmjz54v46/2/1
![image](https://github.com/edosdigital/issues/assets/151843786/d7a5445f-d23a-4148-8ae8-f1c5493dd3c4)

**To Reproduce**
1. Login using this account (gosu auth)
user: dummynick6+1@gmail.com
pass: gamerscrew1!

2.. Go to this tournament and try to submit a score
https://battle.staging.gosugamers.net/tournament/4b0fba70z94srr5p2q1hz8z15j
3. It shows successful message but score wasn't actually been submitted

**Expected behavior**
Score submission should works fine

**Screenshots**
https://drive.google.com/file/d/1Bz0U78Kd0jK3XHadwOUHFLHe60R8g3mT/view

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/4b0fba70z94srr5p2q1hz8z15j

**Comment by EJNiones** [comment]
Confirmed fixed:

https://gyazo.com/6189bb62c999a5ddef9bf6f0b0257f78
https://gyazo.com/548c49c1318b066149b695b915a447ec
https://gyazo.com/18c65c8aa93513f67ed9f7e7acb59672
