### ISSUE TITLE
[Bug] Score that was enforced doesn't show properly

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#108]
**Describe the bug**
I'm an admin trying to enforce a score for this tournament with a best of 3 rules, after score was enforced it doesn't show properly on admin side

1. I enforced a score 5-1 which **tester05 got 5 points**, after submitted it shows that **tester05 got 1 points** while **player 1 got 2 points**
https://gyazo.com/9f5eb55d78fe6bb2d1f898cc801ee0e5

Also the order of player on score enforce prompt seems to be wrong, tester05 score field should be on the right as same as shown in the match
![image](https://github.com/edosdigital/issues/assets/151843786/14219085-9336-40b4-b67f-5633ed873d40)

2. Another weird encounter
https://gyazo.com/afc079d3ee64d51611edaefedc00f126

You can try re-enforce a scores around round 2 to see what's happening 

**To Reproduce**
1. Go to https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=446pwhmnyqnjdy6vcvgdd7d740
2. Try enforce a different score on round 2

**Expected behavior**
Score should reflect properly with what has been submitted

**Screenshots**
Screenshot from Kimoy
![image](https://github.com/edosdigital/issues/assets/151843786/cf994ff5-6394-4b8b-bbe0-a17b484d7729)

**Comment by Yusuf-** [comment]
@JayWongjedjan  This got fixed in the latest push. You can test this with any match in this tournament https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=446pwhmnyqnjdy6vcvgdd7d740

**Comment by EJNiones** [comment]
Confirmed fixed:

https://gyazo.com/2dc841267ed0d39c80762bbb4771c127

https://gyazo.com/0cb8499a7f69960bf7bf84c87b55ae2a
