### ISSUE TITLE
[Bug] Team captain role passed to a member without team role but the new team captain can now see the manage registration status.

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#112]
**Describe the bug**

To Reproduce
1. Register a complete team to a tournament
2. Pass the team captain role to the member with no role in the team
3. The registration management is passed to the new team captain

**Expected behavior**
Since the account doesn't have a team role, he shouldn't be able to see the manage registration status and the registration management should stay to the owner/manager's account.

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://prnt.sc/Ncs0pHWKP25Y

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/46svxc4wftnp5xnzsyk43p4sdn

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by AydinE** [comment]
@EJNiones As far as I know this is working exactly as intended. The person who is "captain" in the context of the tournament gets to manage and execute actions on behalf of the team for that tournament only. This is completely separate from a captain on the team itself which perhaps should be called team manager instead to make this difference more clear.
