### ISSUE TITLE
[Bug] 1 player cannot ready up in round 2 (round 1 not finalize)

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#126]
**Describe the bug**
1 player cannot ready up in round 2 (round 1 not finalize) while another player can ready up just fine

**To Reproduce**
1. I create a tournament in auto mode
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=41w6shk7enjqas8btahn601nm1
2. I enforce a score on match 1 and 2 so that both of my accounts will be matched together in round 2
3. I manually start round 2
4. When the match is in a ready up state, my account Jaytest005 was able to ready up, while another account Clumsycat received error as shown in the screenshots, after a couple refreshes and attempts it still doesn't works, but then the ready up just success somehow

**Expected behavior**
Both player should be able to ready up without any error

**Screenshots**
![image](https://github.com/edosdigital/issues/assets/151843786/0e992574-75dc-4383-a47b-ab1c733db5c4)

## Tournament URL/ID
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=41w6shk7enjqas8btahn601nm1

**Comment by EJNiones** [comment]
https://gyazo.com/ba87d82c5f6e0036ee69c65507474c68
