### ISSUE TITLE
[Bug] Registration does not open on appointed schedule - FFA automated

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#129]
**Describe the bug**
Created Auto tournament didn't open registration automatically at the set open time

**To Reproduce**
1. As an tournament admin, create a FFA tournament with automation active
2. Set a scheduled opening for registration
3. On the tournament page, wait for the appointed schedule 
4. Upon the appointed schedule, registration still not has opened

**Expected behavior**
Registration should open on the exact time as the scheduled time

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/e436d4868d219c101e7466c52c1693a6

https://gyazo.com/f6e05b04008f4fb9324c8ceb4d81aca1

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/49916bdeadtq2zffzrhf2mm9c7

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**
Scheduled opening for registration is also not showing up on the context card

**Comment by AydinE** [comment]
Very likely related to #135

**Comment by EJNiones** [comment]
Fixed:

https://gyazo.com/bf659cba2114d7ed45a2c33e7fd0423f
