### ISSUE TITLE
[Bug] FFA - Unable to enforce scores on match 2 onwards

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#131]
**Describe the bug**
_Enforcing scores from Match 2 onwards in FFA results in error._

**To Reproduce**
_1. I am a tournament admin
2. I have created a live FFA tournament (manual mode)
3. I have added multiple matches for a round
4. I am now enforcing scores for match 2 round 1
5. On the admin panel I attempt to enforce scores on match 2
6. See error_

**Expected behavior**
_Able to score normally on every match for FFA_

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/9c4d57a57daf9c85ecc73dc93f858281
https://gyazo.com/5102c26cca150422b435963f187e9d2b

## Tournament URL/ID
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=4kabx64m8t5024xh5ed80mjqxc

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by Yusuf-** [comment]
Just pushed a fix for this. Can you retest with the same tournament again? @EJNiones

**Comment by EJNiones** [comment]
Confirmed fixed:

https://gyazo.com/b533ec2bcde6811175c4216eddc56b6e
