### ISSUE TITLE
[Bug] FFA individual scoring when submit team score it's also being applied to the first player's score

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#133]
**Describe the bug**
When I try to submit a team score in FFA, when I input the team score the score also gets applied to the first player's score, or if I input the first player's score it also gets applied to the team scores. This only happens to the first player 

**Screenshots**
https://gyazo.com/ed2fdb8affc5fc1378302fc53792b8e8

## Tournament URL/ID
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=41jfthdrr2aqh4fcngn1sjp6w0

## Tournament Type
FFA

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/da48cf9321373e499449e9751d3d84b2
https://gyazo.com/eb8cb9f8d7b6d5a06a11ec9c1eecd8ca
