### ISSUE TITLE
[Bug] Registration did not open on automated SE

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#135]
**Describe the bug**
_Auto SE tournament registration didn't start at the set start time_

**To Reproduce**
_1. Create a SE tournament with automation turned on
2. Set a registration start date and time
3. Publish tournament
4. Wait for the registration start schedule 
5. Registration did not open automatically_ 

**Expected behavior**
_Tournament registration should automatically open when tournament automation is on_

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/7e146aa67132696353a39b25990ced62

https://gyazo.com/9bac4f9bb01e21ea9e1463db57dbcc2f

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/480dknpjpwb9js4sxkxxb732de

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by AydinE** [comment]
@EJNiones Please re-test with a new tournament

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/8015b891f30eedfe25c369a17a1a1bdd

https://gyazo.com/e8d0291492406de0f1c031428cd4238f
