### ISSUE TITLE
[Bug] Ready up / submit scores context card is replaced with "you're registered" context card during a live tournament

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#147]
**Describe the bug**
During testing a SE tournament, the live matches context card were replaced with "you're registered" context cards. This prevents participants to submit scores or access the ready up button 

**Screenshots**
https://gyazo.com/befc42dc8bedeaa1a561e91ae48249e7

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/4jk4w98b3970w4srs35nf0w4dk

https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=4jk4w98b3970w4srs35nf0w4dk

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by kerlos** [comment]
I want step to reproduce on this even on tournament creation and step to find this issue

**Comment by EJNiones** [comment]
Unable to replicate issue anymore.

Closing this report for now.
