### ISSUE TITLE
[FEATURE] To show incomplete team on participant list as pending

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#156]
**Is your feature request related to a problem? Please describe.**
The incomplete team is now not showing under the participant list on the tournament page. 

**Describe the solution you'd like**
Display incomplete teams under the participant list on the tournament page. 
- These incomplete teams should be listed at the bottom of the participant list if there are other successful registered team
- These incomplete teams will be marked as (incomplete)
- If possible the incomplete team should be standout from the complete list

![image](https://github.com/edosdigital/issues/assets/151843786/f13038b7-382b-423f-bc47-df0438553fda)

**Comment by EJNiones** [comment]
Confirmed implemented:

https://gyazo.com/b68fbb7b5f6810933222c807a4328ce2
