### ISSUE TITLE
[Bug] Solo player is marked as incomplete

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#161]
**Describe the bug**
Incomplete shouldn't be marked for solo player

![image](https://github.com/edosdigital/issues/assets/151843786/48bf5dfe-584c-49f9-a48b-9d50cf74f801)

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/4vz30ss7mw6sqwdrter6hz81xy#schedule

**Comment by AydinE** [comment]
If tournamentRegistrationType = Solo we should not be showing this, as registrationComplete is only used for team based tournaments.

**Comment by pai-nuneza** [comment]
This is now for review 
PR: https://github.com/edc-mudblazor/blazor-frontend/pull/413

**Comment by EJNiones** [comment]
Fixed:

https://gyazo.com/3d1b41b9450aee86e4da3d83b6bcf6b7
