### ISSUE TITLE
[Bug] Registration did not automatically open on tournament with automation enabled

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#162]
**Describe the bug**
Set a specific schedule to tournament registration open with a tournament that has automated enabled. Upon reaching target schedule, registration did not automatically open.

**Screenshots**
https://gyazo.com/d1eb987eb3835076f8ef022b319ef5a7

https://gyazo.com/7a96c19b54852a202f1f41955106703d

https://gyazo.com/0da29756f3b2140da3f32001f4716d2f

https://gyazo.com/a55b0b97d76634f96017e790876aff6e

## Tournament URL/ID
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=4bp39savh3zpf020gzrn8vgdmw

**Comment by AydinE** [comment]
@EJNiones Tournament should now have gone live, this is a very big edge case that should only happen because of weird timing with server restarting at the wrong moment. We have looked into this and will keep an eye on it but it won't need a "fix" for now.
