### ISSUE TITLE
[Bug] Ready Up Timer is showing up on match page even if ready up phase has not yet active

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#165]
**Describe the bug**
On manual mode tournament, the ready up timer is showing up on the participants match page even if the match  / ready up phase hasn't been started. The timer is static and will not count down.

**To Reproduce**
1. Create an SE or DE tournament with automation turned off
2. Register participants
3. Make tournament live
4. Make current round live but do not start any matches yet
5. Go to the tournament page and enter one of the upcoming match pages
6. Once on the match page, the counter down timer will show but will not move

**Expected behavior**

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/8768529cee80ff92cebe629e9d7dfc26

https://gyazo.com/f9d0ea943e339e6187bb93fcfcfc9510

## Tournament URL/ID
Provide the tournament ID or Url if applicable

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by pai-nuneza** [comment]
for review
PR: https://github.com/edc-mudblazor/blazor-frontend/pull/429

**Comment by EJNiones** [comment]
Fixed:

https://gyazo.com/a96e4cc60eb3e55bbadbd813b54d5a5b
