### ISSUE TITLE
[Bug] Tournament prize image is not working 

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#167]
**Describe the bug**
After adding a prize image it doesn't show on the tournament page.

![image](https://github.com/edosdigital/issues/assets/151843786/ebdae1af-9c15-4a87-81ad-62e6f681ab8c)

https://battle.staging.gosugamers.net/tournament/4qs77k9s0mqr70fg0kg1n1xm4h

**Comment by EJNiones** [comment]
Fixed:

https://gyazo.com/fbe82d3b092b9d1245882dba36d596d2
