### ISSUE TITLE
[FEATURE] Add a confirmation prompt for starting - deleting - finalizing tournament

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#171]
**Is your feature request related to a problem? Please describe.**

Add a confirmation prompt when the user is trying to perform any undoable action to avoid any misclick
- Start tournament (on admin management)
- Finalize tournament (on admin management)
- Delete tournament (on tournament list)

![image](https://github.com/edosdigital/issues/assets/151843786/020e1fee-fb14-4446-a428-8402541fb784)
![image](https://github.com/edosdigital/issues/assets/151843786/d27f35b9-aca8-48a7-9d50-c737af8449b9)

**Comment by EJNiones** [comment]
Feature implemented on Start tournament action:

https://gyazo.com/c4cb8e60cc893a7f68f981f06922d8b1

Finalized tournament action:

https://gyazo.com/f63d4246f8e85a0faf8d212229f46c35

Still not implemented on delete tournament action:

https://gyazo.com/fff97a14164532b7d7b3b1b88113de4f
