### ISSUE TITLE
[FEATURE] Manual register player input field should be ready to input without clicking on the input field first

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#172]
**Is your feature request related to a problem? Please describe.**
- Make the participant ID field ready to input without clicking on it first, right now I need to click on the input field to make it typable which is a bit annoying if I have to register a lot of teams
- Hitting enter should also work as a confirm button

https://gyazo.com/2f346d920b1a2dcd73ef3e36605c21da

**Comment by EJNiones** [comment]
Feature implemented:

https://gyazo.com/9aec5421821c2bd8fac1f46efd0e1d53
