### ISSUE TITLE
[Bug] Team list under FFA matches (admin) is showing UID instead of Team name

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#173]
**Describe the bug**
On FFA admin management, the team list under matches supposed to show the team name instead of UID

![image](https://github.com/edosdigital/issues/assets/151843786/94969eb1-85bf-4175-b56b-9f89a98ebb35)

**Comment by EJNiones** [comment]
UI Update fixed issue:

https://gyazo.com/d4f85d1e0e9ce67d450af97462e6c471

Team name is now displayed above TID/UID
