### ISSUE TITLE
[Bug] Adding images under rules section is not working

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#174]
**Describe the bug**
After attaching an image in the rules section under tournament wizard, once I saved and looked at the tournament page the image wasn't displayed but show file name instead

![image](https://github.com/edosdigital/issues/assets/151843786/8e176cb7-14d3-42d9-b02b-e9881b6b6ce7)
![image](https://github.com/edosdigital/issues/assets/151843786/454baa7f-5f17-4835-990a-538cbeb47f1a)

Tournament link:
https://battle.staging.gosugamers.net/tournament/44ftt06s073jg6nptw1csd6m4z

**Comment by EJNiones** [comment]
Fixed:

https://gyazo.com/dd9b003b5b6dab2c0835c7d849d7f6cb
