### ISSUE TITLE
[Bug] FFA did not show custom score info while submitting scores

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#212]
**Describe the bug**
I'm a player attempting to submit a score in FFA tournament. I see score submission field but it doesn't tell what score am I submitting for

![image](https://github.com/edosdigital/issues/assets/151843786/453a7b1d-a6ab-48e8-9d94-36e97554915f)
![image](https://github.com/edosdigital/issues/assets/151843786/d214f2ea-7fb1-4507-a06e-81d594112726)

## Tournament URL/ID
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Wizard?tournamentId=4heeaxyyxfzyj7ncskhm8kwddy

## Tournament Type
FFA

**Comment by EJNiones** [comment]
Custom Scoring fixed:

https://gyazo.com/7cdea4dd086bc515bcd4ee568d47b030

https://gyazo.com/6e49eb7db9113d00fd3288ef9c91492e

https://gyazo.com/41db258c85b90ee90e8d04de729c1597
