### ISSUE TITLE
[Bug] FFA - Added groups from round one will not show up once another round has been added.

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#222]
**Describe the bug**
The groups that were added on round one will disappear once another round is added. 

**To Reproduce**
1. Create a FFA tournament
2. On round one, add at least one additional group
3. Add another round
4. Go back to round one tab
5. Retry to assign members to groups on round
6. The added groups are not showing up on the assign participants window

**Expected behavior**
The added groups will remain visible even after adding new rounds
## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/01945bf7db9b0750da44be4d884cccc5

https://gyazo.com/1e649dbd8a14ac4fd54a75dc22d5312f

https://gyazo.com/0b10dbb1964d50b68283eb3bcd3d0372

https://drive.google.com/file/d/1Sd4O__3_FcF3jv8AP1vekCLGH2WdYO_X/view

## Tournament URL/ID
Provide the tournament ID or Url if applicable

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by JayWongjedjan** [comment]
Duplicate ticket

**Comment by JayWongjedjan** [comment]
This ticket is duplicate please leave it as closed
