### ISSUE TITLE
[Bug] Max participants should never go below 0 participants

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#26]
**Describe the bug**
When using the arrow keys when setting amount of participants, counter should not go below 0 participants (negative number)

**To Reproduce**
1. On tournament wizard create a tournament
2. On tournament info, select the max participants tab
3. Using the down arrow key, press it until the number goes below zero and to negative status

**Expected behavior**
Max participants should not go below zero

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/71713ecf5847252f0cffd131762a4d83

## Tournament URL/ID
Provide the tournament ID or Url if applicable

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by AydinE** [comment]
This should already no longer be possible, but also this is some common sense stuff for the organizer.
