### ISSUE TITLE
Socials should have space provided for html links 

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#29]
**Is your feature request related to a problem? Please describe.**
The socials tab only have space for text input and not able to handle html links to social profiles

**Describe the solution you'd like**
Any html links provided on the socials tab should be clickable and able to divert users to the provided link address

**Describe alternatives you've considered**

**Additional context**
With the current design, users needs to copy and paste the provide links to be able to visit the social links provided

**Comment by JayWongjedjan** [comment]
Social link are now clickable 
https://github.com/orgs/edosdigital/projects/11?pane=issue&itemId=45849993
