### ISSUE TITLE
[Bug] Enforced scores on match 1 but match 2 also have scores of match 1

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#40]
**Describe the bug**
I try to enforce score on admin side for match 1 but after checking on the schedule page the scores that was submitted also show on match 2 (try enforce score on match 2 still doesn't change)

**To Reproduce**

**Expected behavior**

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/c5661dcb273ba31c3adda8ad1d0117c2

## Tournament URL/ID
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=4jh1rg5sr6hj733znp7js0pgcn

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by Yusuf-** [comment]
@EJNiones this seems to be fixed https://battle.staging.gosugamers.net/tournament/4jh1rg5sr6hj733znp7js0pgcn
Can you retest again?

**Comment by EJNiones** [comment]
Confirmed fixed:

https://gyazo.com/33b3437b63aa4bf0d9df00560c0a96ec
