### ISSUE TITLE
[Bug] Missing Ready Up and Submit Score buttons

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#42]
**Describe the bug**
When round starts, the ready up button section is missing. When round is live, the submit score button is missing.

**To Reproduce**

**Expected behavior**

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/b35c517ef01f16f182daf33d90921cfb

https://gyazo.com/40db2de710dd3fcf73342c7a4b30b9e8

## Tournament URL/ID
[Provide the tournament ID or Url if applicable](https://battle.staging.gosugamers.net/tournament/4tfdwy85e0nbq701d2gd93cvmj)

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by kerlos** [comment]
there's no match in this tournament

**Comment by EJNiones** [comment]
Created a new FFA tournament for this bug:

https://battle.staging.gosugamers.net/tournament/4h8r4rb9kc84f4bx47pqnv0qc7

But cannot test it properly because of issue #97 

https://gyazo.com/5e786412cacb35d5f84d06bab18e3e4f

@kerlos

**Comment by EJNiones** [comment]
This issue has been fixed:

https://gyazo.com/5ed9c7b586ae86c6ef35d607bdaaed92

https://gyazo.com/f649ebb59cece02ab3ad9178157f4470
