### ISSUE TITLE
[Bug] Removed participant still show under match player list

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#43]
**Describe the bug**
Assigned a participant into group and remove this participant before tournament starts. After tournament start it shows a blank participant under match player list 

**To Reproduce**
- I assign Sean into group 2
- I remove Sean from the tournament
- The icon where it supposed to be Sean still there but empty. Can be resolved by unassign this player from the group
https://gyazo.com/5508d84a1c03c67723bb40b2c9373b10
https://gyazo.com/e64d137d847877ff3825acea08b4299e
https://gyazo.com/b80940c9e4e5b16619be4abb3eaa0e30"

**Screenshots**
https://gyazo.com/2ad823334cf75fb0b32726bc48d09bc9

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/49r6b0mka5m5qzd697d80bxcm7

## Tournament Type
FFA

**Comment by Yusuf-** [comment]
I pushed a fix for this. Can you test this again? @EJNiones

**Comment by EJNiones** [comment]
Confirmed fixed:

https://gyazo.com/f4c4061fe42c5f5ff1eb4be678156f5d

https://gyazo.com/75b28c40f26dbdd517adf174ef5af03f
