### ISSUE TITLE
[Bug] Missing submit scoring options on match page

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#44]
**Describe the bug**
Once both player readied up there's is no submit score button on the match page, it shows up if you go back to tournament page

**Screenshots**
https://gyazo.com/21b78a6f6a22db59bb5f744dc2dbbda2

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/49r6b0mka5m5qzd697d80bxcm7

## Tournament Type
FFA

**Comment by kerlos** [comment]
If able. press F12. in console message look for  read text block and capture that too

**Comment by kerlos** [comment]
issue not found. maybe solved by BE
