### ISSUE TITLE
[Bug] Match is on ready up but admin panel still show status as upcoming

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#45]
**Describe the bug**
Match already on ready up phase but admin panel is still showing upcoming status. Page refresh changes the status.

**To Reproduce**
1. On an upcoming FFA tournament, set a round start time and match start time
2. On the admin match panel, upon reaching scheduled start time, check the status of the match (it still on upcoming)
3. Refresh the page
4. Will see the status as Ready Up now.

**Expected behavior**
Status should update without need to refresh page

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/f8e2595ea3f3c6634884d3c22398e6cc

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/4cz055wzew0tfzj1qzf2xybpxp

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by kerlos** [comment]
BE match state didnt change

**Comment by AydinE** [comment]
@EJNiones Please recheck this and verify, ad more info like tournament ID etc. if still exists

**Comment by EJNiones** [comment]
Updated the report.

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/1fd14a07df32e4243fec1968952b738d
