### ISSUE TITLE
[Bug] Image sent in chat didn't show on admin side

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#49]
**Describe the bug**
When a player sent any image in the match chat it appears as a file name on the admin side

**Screenshots**
![image](https://github.com/edosdigital/issues/assets/151843786/cc2b68a8-e369-43b0-b578-ae8f1e86ceb4)

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/061fa949150b88f1e3c0353bb3816d51
