### ISSUE TITLE
[Bug] Game Icon Broken/Missing

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#52]
**Describe the bug**
Game icon is missing/broken when users link their game accounts (Valorant/CS:GO)

**To Reproduce**
1. On the user's profile page. click on the edit button for Valorant or CS:GO (If already linked)
2. Will see icon for it is broken

**Expected behavior**
Icons for this games should not be broken

**Screenshots**
https://gyazo.com/88ed7fc451e19a58e59f88d11b25b0ac
https://gyazo.com/0ea605d5a535bcde1af80d22b18f1b5b

**Comment by kerlos** [comment]
BE

**Comment by AydinE** [comment]
The problem here I think is that game icons are being uploaded to the root folder of the media library, try again with proper folder structure
