### ISSUE TITLE
[Bug] Registration notification does not appear after registering to a tournament

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#54]
**Describe the bug**
Notification will not appear even after refreshing the page. 

**To Reproduce**
1. Go to a live tournament page with registration open
2. Register for the tournament
3. No notification is received

**Expected behavior**
A  notification prompt should appear on your notifications tab

**Screenshots**
https://gyazo.com/b9b129496f2efccc836b96d39d80b1ab
https://gyazo.com/74921865faa9de4acdf2d4fcd7f70460
https://gyazo.com/d6737bd20d64547605d5a70e3a16223a

**Comment by AydinE** [comment]
@EJNiones Not really a bug these notifications are just not set up currently in the workflows
