### ISSUE TITLE
[FEATURE] Change CS:GO to Counter Strike 2

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#57]
**Is your feature request related to a problem? Please describe.**
CS:GO is now replaced as Counter Strike 2 on Steam Platform and all live tournaments

**Describe the solution you'd like**
Change the game name and logo to the Counter Strike 2 one

https://gyazo.com/f06870303b23586bcabb0851a4b6e83b

**Comment by AydinE** [comment]
@EJNiones This is done on the admin panel
