### ISSUE TITLE
[Bug] Team invite is lost when dismissing team invite notification 

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#58]
**Describe the bug**
When receiving a team invite notification, if user clicks on the notification but does not accept and then refreshes the page, the notification and invite will disappear even if click the notifications tab again.

**To Reproduce**
1. Receive a team invite notification
2. Click on the notification tab 
3. Do not accept notification 
4. Refresh page
5. Click on the notification again
6. Notification is now empty

**Expected behavior**
Team invite/notification will still be present even after page refresh

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/01f062d4f7d4f8e58834969bb59d299a

## Tournament URL/ID
Provide the tournament ID or Url if applicable

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by AydinE** [comment]
@EJNiones It's not lost, going to the team page directly you will still see the invite and be able to accept/decline
