### ISSUE TITLE
[FEATURE] After score is submission, context card shows that the opponent is reviewing the scores instead of admin reviewing scores

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#67]
**Describe the bug**
Context should be changed to "The score has been submitted. Please wait while the admin is finalizing the scores" since there is no score confirming flows in FFA

**Comment by kerlos** [comment]
this was fixed sometime ago. please test again

**Comment by EJNiones** [comment]
Unable to confirm fix

Unable to submit score on participants side 
https://gyazo.com/bfc3871cbf5e69d9286bd4e2704ce5be

https://gyazo.com/5b98d23a924fa15b0689382360c55587

No error messages are received on platform but submit score is not processing.

**Comment by EJNiones** [comment]
Confirmed implemented:

https://gyazo.com/21b70a3f6032da6c6fa8e8011e623374
