### ISSUE TITLE
[Bug] Match is live but context card and schedule did not update

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#68]
**Describe the bug**
Context card is updated on page refresh

**Screenshots**
https://gyazo.com/43688cd1de09942582b38eb82e56f4ff

**Comment by kerlos** [comment]
note. fix but it's may not working

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/89d0cc7c5e25e1b6ae9ef32b3f5c133b
