### ISSUE TITLE
[Bug] After past match start time the admin panel still show as upcoming

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#75]
**Describe the bug**
On the admin panel once the match is already past start time it still show as upcoming instead of live. Need a refresh to see the updated status

**To Reproduce**
1. Set up FFA tournament
2. Create group, matches and assign player to group
3. Schedule a match start time
4. After past match start time it still show as upcoming instead of changing to live
5. Match status update after refresh

**Expected behavior**
After past scheduled time the match status should update real time

**Screenshots**
![image](https://github.com/edosdigital/issues/assets/151843786/f50e2cb2-f8b6-4b30-b18a-d8492a87e5cf)

## Tournament Type
FFA

**Comment by EJNiones** [comment]
Issue Fixed:

https://gyazo.com/694f354e81ab1c6a3352dfce182e7ecb
