### ISSUE TITLE
[Bug] Leaving a team tournament does not update context card

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#76]
**Describe the bug**
After manually leaving a team tournament, the registration card does not update. A page refresh is needed.

**To Reproduce**
1. I Register to a team tournament
2. On the team registration page,  I click on leave tournament button
3. I press yes on the leave tournament prompt
4. I am unregistered to the tournament but the context card is still showing am registered

**Expected behavior**
After leave the team tournament, context card should already show the register button

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/46e7f4f6de7ed941ac000058639e5884

## Tournament URL/ID
Provide the tournament ID or Url if applicable

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by EJNiones** [comment]
Issue still present:

https://gyazo.com/e974f0e71567803ab032fc9279820caa

Is fix already deployed @kerlos ?

**Comment by kerlos** [comment]
it just got merged recently maybe not deployed yet

**Comment by EJNiones** [comment]
Fixed:

https://gyazo.com/b15573ec1728a88ab391c17c9c6f74dd
