### ISSUE TITLE
[Bug] Tournament Wizard - Manually opening registration results in error 

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#84]
**Describe the bug**
_When attempting to manually open registrations for a tournament, we receive an error "Something went wrong while opening registrations: tournament must have 2 participants". This should not be the case since the tournament has been set with maximum participants of 8 and has yet to open for registration._

**To Reproduce**
_1. I am an tournament administrator 
2. I have created a team tournament with a maximum participants that is above 2
3. On the tournament management panel I attempt to manually open tournament registration
4. See error_

**Expected behavior**
_Manually opening tournament should not be blocked by this error since tournament has yet to receive participants_

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/e0bf479f32e109ff3c624e3a091e0df2
https://gyazo.com/48f50ced8e0833bad4ce1c625d5323fc

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/43cf32p651zrx6mcwpenygfsmd

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**
_This error also emerge when trying to create a team tournament:_
https://gyazo.com/ac5ee09aeb4a6543862d8376b0656ff6

**Comment by AydinE** [comment]
Please check again if this is fixed now

**Comment by EJNiones** [comment]
Issue has been resolved.
