### ISSUE TITLE
[Bug] Notification gone blank after clicking on one notification

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#87]
**Describe the bug**
When I receive any notification and click on it, when I click on the bell notification again the notification just goes blank, need a couple of refresh to be able to see the list of notification again

**To Reproduce**
1. Click on bell notification and select any notification
2. Click on bell notification again
3. List of notifications gone missing

**Expected behavior**
Everytime when you click on bell notification it should always show the list of notifications

**Screenshots**
https://gyazo.com/ec4a9551363a50b03b2ddb67189560c0

**Comment by pai-nuneza** [comment]
This is now for review.
https://github.com/edc-mudblazor/blazor-frontend/pull/415

**Comment by pai-nuneza** [comment]
Still checking on the initialization of the notifications

**Comment by EJNiones** [comment]
Fixed:
https://gyazo.com/d7352922ce4bf821858eb218cc8230b3
