### ISSUE TITLE
[Bug] A player role still able to register/unregister team to the tournament 

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#88]
**Describe the bug**
- I'm a team owner, I created a team and transferred ownership to another account, so I am now a team manager 
- The new team owner unassign me from the team manager so I am now just a player
- I am still able to register/unregister this team for the tournament

So again I tried to use the new team owner to kick me out of the team and invite me again
Yet I am still able to register or remove this team for the tournament

**Expected behavior**
- Player role shouldn't be able to register or unregister the team for the tournament

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/67d9b89b62adfcefb51b6eeab26ddf20
https://gyazo.com/a1f0392c3abd1c16eaa1b89fd01b2e4a
https://gyazo.com/88ef1ba381765df0edb3beec6fead877
https://gyazo.com/dd2a78fe263a33600c94a4a7a1418608
