### ISSUE TITLE
[Bug] After kicking player from the team, the tournament still shows that the registration is completed

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#89]
**Describe the bug**
Once I registered the team to the tournament, and kicked the team roster from my team, the context card still show as registration completed instead of Almost There to tell that the team roster is missing

**To Reproduce**
1. Register team for the tournament with 2 roster
2. Kick 1 roster from the team
3. When looking at the tournament page it still shows that the registration is completed 

**Expected behavior**
When the roster got kicked from the team, the context card should update to tell that the registration is still not completed

**Comment by AydinE** [comment]
Don't allow kicking player from team or leaving team if they are registered to an active or upcoming tournament
@Yusuf-

**Comment by EJNiones** [comment]
Fix verified:

https://gyazo.com/1daa3b81790ae8f2bda020b80b0689db
https://gyazo.com/cdfb9a48028f1f02c54f819301355065
https://gyazo.com/91c9facd8b3210a8d6c27e0a6170ba3b
