### ISSUE TITLE
[Bug] Match count down timer is showing on tournament schedule page but not on the actual match page

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#90]
**Describe the bug**
_Admin has scheduled a match start. On the tournament schedule page, the count down timer is visible but when going to the actual match page the timer is not preset._

**To Reproduce**
_1. I am registered to a tournament and has a match coming up
2. Tournament admin sets a start date/time for that match
3. I go to the tournament's schedule tab and look up my upcoming match
4. I see a count down timer on that match tab
5. I then go to the actual match page
6. I do not see the count down timer_

**Expected behavior**
_Count down timer should also be present on the match page_

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/997f52d1c23fbc15445687c40f01c5a8

## Tournament URL/ID
Provide the tournament ID or Url if applicable

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**

**Comment by kerlos** [comment]
-what type of tournament
-which tournament url

**Comment by EJNiones** [comment]
Tournament url: https://battle.staging.gosugamers.net/tournament/474m7cn5gf4hy2a33pybxtbddb/2/1

Tested on SE type

https://gyazo.com/4f9c3d63743642fa5c1216f66d7910eb

**Comment by pai-nuneza** [comment]
Hi @AydinE, PR for review. 
https://github.com/edc-mudblazor/blazor-frontend/pull/423

**Comment by EJNiones** [comment]
Fix implemented:

https://gyazo.com/a96e4cc60eb3e55bbadbd813b54d5a5b
