### ISSUE TITLE
[FEATURE] Able to unselect player from the player list at the team registration

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#91]
**Is your feature request related to a problem? Please describe.**
When the rosters are being selected, if they don't have a player profile uploaded it's impossible to define who is being selected and hard to remove the right player from the icon list. So requesting to be able to unselect the selected player from the player list below 

![image](https://github.com/edosdigital/issues/assets/151843786/9483f02b-3f62-42b9-9346-eb57768807e9)

**Comment by EJNiones** [comment]
Implemented:

https://gyazo.com/f8c30afb4680b0112b0eb9d626876def
