### ISSUE TITLE
[Bug] Unable to submit a score with screenshot attached

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#92]
**Describe the bug**
I am a player trying to submit a score with jpg screenshot but I receive an error when I hit submit. When I remove all the attached files I can submit just fine

**Expected behavior**
score should be submitted without any error

**Screenshots**
![image](https://github.com/edosdigital/issues/assets/151843786/448b0f09-92fb-43b4-bdd3-a8e4c2979622)

## Tournament URL/ID
[Provide the tournament ID or Url if applicable](https://battle.staging.gosugamers.net/tournament/46v8652pspxb9xc0s51m69yd5h)

## Tournament Type
FFA

**Comment by kerlos** [comment]
@JayWongjedjan  please  validate if this problem still occurred

**Comment by EJNiones** [comment]
@kerlos - Unable to submit score on participants side and unable to confirm the status of this bug: 

https://gyazo.com/bfc3871cbf5e69d9286bd4e2704ce5be

https://gyazo.com/5b98d23a924fa15b0689382360c55587

No error messages are received on platform but submit score is not processing. 

Fix block by #144

**Comment by EJNiones** [comment]
Confirmed fixed:

https://gyazo.com/8d37a2a62e3dcc4f160b994d0a46f461

https://gyazo.com/608694eadc4e5ef007d07aa33af872cf
