### ISSUE TITLE
[Bug] Unable to enforce a score in FFA match

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#93]
**Describe the bug**
I'm an admin trying to enforce a score in FFA match but I receive error 

**To Reproduce**
1. Go to this admin management https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=46v8652pspxb9xc0s51m69yd5h
2. Try enforce scores on Round 1 group 1 match 1
3. Received error 
![image](https://github.com/edosdigital/issues/assets/151843786/5fd142f5-40c8-4da2-85ea-1cd554c036c4)

4. The score of this match has previously been reported by Clumsycat before I try to use admin management to enforce a scores

**Expected behavior**
Admin should be able to enforce scores for this match without any issues

**Screenshots**
https://gyazo.com/16fb09d5310b4335fd6cfe3bd3c1d7bf

## Tournament URL/ID
https://api.battle.staging.gosugamers.net/Admin/Edos.OrchardCore.TournamentModule/Nav/Manage?tournamentId=46v8652pspxb9xc0s51m69yd5h

## Tournament Type
FFA

**Comment by Yusuf-** [comment]
@JayWongjedjan This issue is fixed, but only works for new tournaments. Can you create a new FFA tournament and check if this issue still occurs?

**Comment by EJNiones** [comment]
Confirmed issue is fixed.
