### ISSUE TITLE
[Bug] Incorrect winner placement for finalized DE tournament

### ISSUE THREAD

**Issue by EJNiones** [edosdigital/issues#95]
**Describe the bug**
_The overall tournament winner placement is given to the lower bracket participant if they win the first round of the finals match but lost on the second finals round._ 

**To Reproduce**
_1. As an admin on an DE tournament on its finals match between upper bracket winner and lower bracket winner
2. On round 1 finals match, give winning point to the lower bracket participant
3. On tournament panel, activate the second finals match 
4. On round two finals match, give the winning point to the upper bracket participant
6. See error on the tournament's participants tab. You will see that the lower bracket participant is overall first place instead of bein second place._

**Expected behavior**
_Upper bracket participant should still receive overall winner status even if they lost the first finals round._

## Priority
Tag the priority on the right ->
Please only use High when it's actually high 

**Screenshots**
https://gyazo.com/b0e1929a02d8f65bde4bf7d86a4ce058
https://gyazo.com/1c0df7871f75b3274566ca836ba9d790

## Tournament URL/ID
https://battle.staging.gosugamers.net/tournament/4xpgvesq0ddks38y4hm02eef44

## Tournament Type
If it is a tournament relation issue choose the tournament type on the right ->

**Additional context**
_Rule for DE tournament is: "participants needs to lose twice before getting eliminated"_

**Comment by Yusuf-** [comment]
Fixed it. Check the results in this tournament. 
https://battle.dev.edosdigital.com/tournament/4rx25c8ak0z06rmhrb085vfy47

You can retest it with a new tournament on staging

**Comment by EJNiones** [comment]
https://gyazo.com/897ce06d2b188f08350816379278845a

Fix not yet deployed to battle.staging.gosugamers.net

https://battle.staging.gosugamers.net/tournament/472wdj0zhrrbv144p2m7qadm4e

**Comment by EJNiones** [comment]
Issue fixed:

https://gyazo.com/00155c026c534fe6d9abec770abcd601
