### ISSUE TITLE
[FEATURE] Remove search bar and link icon from team registration

### ISSUE THREAD

**Issue by JayWongjedjan** [edosdigital/issues#99]
**Is your feature request related to a problem? Please describe.**
This is first intended to be an invite flows where you can copy team invite link and send it to other people to accept, or they can use search function to search for any player to invite but seems like we never really have this implemented so I think we can remove the search bar and invite link from manage roster flows

![image](https://github.com/edosdigital/issues/assets/151843786/cd3eea3e-51e9-4cdd-8365-ff47c08c4f95)

**Comment by EJNiones** [comment]
Fix not yet implemented on staging.

**Comment by EJNiones** [comment]
Confirmed Fix implemented:

https://gyazo.com/8e4b490156b3849597e7dfaec9b860c6
